config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :books do
    resources :issue_details

  end
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end#root "devise/sessions#new"

get "about" => "pages#about",:as=>"about"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :issue_details
  validates_presence_of :book_name, :author, :price, :description
  validates_uniqueness_of :book_name

  def self.search(search)
    where('book_name LIKE ?', "%#{search}%")
  end
end

app/models/issue_detail.rb
class IssueDetail < ActiveRecord::Base
  belongs_to :book
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # def after_sign_in_path_for(resource)
  #   home_path
  # end
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      books_path
    else
      super
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(available:true)
    @issue_details = IssueDetail.all.where(returningDate:nil)

    if params[:search]
      @books = Book.search(params[:search])
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show

  end

  # GET /books/new
  def new
    @book = Book.new

  end
end

app/controllers/issue_details_controller.rb
class IssueDetailsController < ApplicationController
before_action :set_issue ,:only => [:show,:update]
  def index
    @issue = IssueDetail.all
  end

  def show
    @book_id=params[:book_id]

  end

  def new

   @issue=IssueDetail.new
   @book_id=params[:book_id]
   respond_to do |format|
     format.js
     format.html
   end

  end

  def update
    debugger
    respond_to do |format|
      if @issue.update(issue_params)
        book = Book.find(params[:issue_detail][:book_id])
        book.available = true
        book.save
        format.html { redirect_to books_path, notice: 'Book returned !!!.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def create

    @issue = IssueDetail.new(issue_params)
    respond_to do |format|
      if @issue.save
        book = Book.find(params[:issue_detail][:book_id])
        book.available = false
        book.save
        debugger
        format.html { redirect_to books_path, notice: 'Book is issued!!!!!!!' }
        format.json { render :show, status: :created, location: @book }

      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_issue
    @issue=IssueDetail.find(params[:id])
  end

  def issue_params
    params.require(:issue_detail).permit(:book_id, :issueDate, :returnDate, :returningDate)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end

  def login

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def check_current_page(path)

    ['sign_in','3000'].map{|n| path.include?(n)}.include?(true) ? false : true
  end

  def get_book_name(booking_id)
     book=Book.find(booking_id)
     book.book_name
  end
end

app/views/books/index.html.erb
<div class="col-md-12">
  <div class="col-md-6">
    <table class="table table-striped">
     <thead class="heading"><tr><th style="text-align: center">AVAILABLE BOOKS</th></tr></thead>
      <tbody>
            <%@books.each do |book|%>
                <tr><td><%= link_to book.book_name ,new_book_issue_detail_path(book.id), remote: true %></td></tr>
            <%end%>
    </tbody>
    </table>
    </div>
  <div class="col-md-6">
    <table class="table table-striped">
      <thead class="heading"><tr><th style="text-align: center">ISSUED BOOKS</th></tr></thead>
      <tbody>
      <%@issue_details.each do |issue|%>
         <%if issue.book.available==false%>
          <tr><td><%= link_to issue.book.book_name ,book_issue_detail_path(issue.book.id,issue.id), remote: true %></td></tr>
        <%end%>
      <%end%>
      </tbody>
    </table>
</div>
</div>

<div id="new-issue">
  <%= render :partial => "issue_details/iss_new_modal",:locals => {:issue=>@issue,:book_id=>@book_id}%>
</div>

app/views/issue_details/_form.html.erb
<%=form_for @issue,url:request.path.include?('new')? book_issue_details_path(@book_id):book_issue_detail_path(@book_id,@issue.id) do |f| %>
    Book name <input type="text" name="issue_detail[book_name]" value="<%=get_book_name(@book_id)%>">
    Book Id <input type="text" name="issue_detail[book_id]" value="<%=@book_id%>">

    <%=f.label "Issue Date"%>
    <%=f.date_field :issueDate%>

    <%=f.label "Return Date"%>
    <%=f.date_field :returnDate %>

    <%if !request.path.include?('new')%>
        <%=f.label "Returning Date"%>
        <%=f.date_field :returningDate %>
        Employee Id<input type="text">
   <%end%>
    <%=f.submit "Create"%>

<%end%>

app/views/issue_details/_iss_new_modal.html.erb
<%if !@issue.blank?%>
<!--<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>-->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Issue New Book</h4>
      </div>
      <div class="modal-body">

        <%= render 'issue_details/form'%>

      </div>

      <div class="modal-footer">
        <div class="actions">
        </div>

        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">save</button>
      </div>
    </div>

  </div>
  </div>
<% end %>

app/views/issue_details/new.html.erb
<%=render 'form'%>

app/views/issue_details/new.js.erb
$('#new-issue').html(" <%=j render :partial => "issue_details/iss_new_modal",:locals => {:issue=>@issue,:book_id=>@book_id}%>")
$('#myModal').modal('show')

app/views/issue_details/show.html.erb
<%=render 'form'%>

app/views/issue_details/show.js.erb
$('#new-issue').html(" <%=j render :partial => "issue_details/iss_new_modal",:locals => {:issue=>@issue,:book_id=>@book_id}%>")
$('#myModal').modal('show')

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <copyright>
      &copy; Consultadd <%= Time.now.year %>
    </copyright>
    <nav>
      <ul>
        <li>Visit Us At   <a href="http://www.consultadd.com/">www.consultadd.com</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.consultadd.com/">Consultadd</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <% if user_signed_in? %>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <%= form_tag(books_path, :method => "get", id: "search-form", :class=>"form-control") do %>
              <%= text_field_tag :search, params[:search], :class=>"form-control", placeholder: "Search Books" %>
              <%= submit_tag "Search", :class=>"btn btn-default", :name => nil %>
          <% end %>
        </div>
      </form>
          <% end %>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><%#= link_to "Home", home_path %></li>-->
        <!--<li><%= link_to "About", about_path %></li>-->
        <% if user_signed_in? %>
            <!--<li><%#= link_to "Book List", books_path %></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Settings</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <link href="//fonts.googleapis.com/css?family=Source Code Pro&subset=latin,latin-ext" rel="stylesheet" type="text/css">

  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%#debugger%>
    <%#= render 'layouts/header' if check_current_page(request.original_url) %>
<%= render 'layouts/header' %>

<div class="container">
      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class:"alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1> What to say about me????? </h1>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <!--<div class="jumbotron center">
    <h1>Welcome</h1>
    <p>Sign up <%= link_to "here", "#", class: "btn btn-primary" %></p>
    </div> -->

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000"  >
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <div class="carouselImg">
          <img  src=<%= asset_path("book1.jpg")%> alt="Books">
            </div>
          <div class="carousel-caption">
            ...
          </div>
        </div>
        <div class="item">
          <img class="carouselImg" src=<%= asset_path "book2.png" %> alt="Books">
          <div class="carousel-caption">
            ...
          </div>
        </div>
        ...
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

</body>
</html>

app/views/pages/login.html.erb
<!Doctype html>
<html>
<head>

</head>
<body>
    <% if user_signed_in? %>
        <%#= render "pages/home" %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% else %>
        <div class="jumbotron center">
          <h1>Welcome Admin</h1>
          <br>
          <p>
            <%= link_to "Login", new_user_session_path , class: "btn btn-default" %>
            <%#= link_to "Sign Up", new_user_registration_path , class: "btn btn-primary" %>
          </p>
        </div>
    <% end %>
</body>
</html>

app/views/return_details/new.html.erb
<%if !@issue.blank?%>
    <!--<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>-->

    <!-- Modal -->
    <body>
    <h1>Page Header</h1>
    <%=form_for @issue,url:book_issue_details_path(@book_id), method: :get do |f| %>
        Book name <input type="text" name="issue_detail[book_name]" value="<%=get_book_name(@book_id)%>">
        Book Id <input type="text" name="issue_detail[book_id]" value="<%=@book_id%>">

        <%=f.label "Issue Date"%>
        <%=f.date_field :issueDate, name="issue_detail[issueDate]"%>

        <%=f.label "Return Date"%>
        <%=f.date_field :returnDate %>

        <%=f.label "Return Date"%>
        <%=f.date_field :returningDate %>
        Employee Id<input type="text">
        <%=f.submit "Create"%>

    <%end%>
    </body>
<%end%>